version: '3'

services:
    db:
        image: postgres:latest
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - mynet

    api:
        build: ./backend
        image: saozp-api
        depends_on:
            - db
        networks:
            - mynet
        ports:
            - '80:3000'
        links:
            - db
        environment:
            DB_CONNECTION_STRING: postgres://postgres:postgres@localhost:5432/postgres

networks:
    mynet:
        driver: bridge

volumes:
    db:
        driver: local
