#x-logging: &default-logging
#  logging:
#    driver: json-file
#    options:
#      max-size: 100m

services:
 server:
  image: judge0/judge0:1.13.1
  volumes:
   - ./judge0/judge0.conf:/judge0.conf:ro
  ports:
   - '2358:2358'
  privileged: true
  #    <<: *default-logging
  restart: always
  networks:
   - mynet

 workers:
  image: judge0/judge0:1.13.1
  command: ['./scripts/workers']
  volumes:
   - ./judge0/judge0.conf:/judge0.conf:ro
  privileged: true
  #    <<: *default-logging
  restart: always
  networks:
   - mynet

 db:
  image: postgres:13.0
  env_file: ./judge0/judge0.conf
  volumes:
   - postgres-data:/var/lib/postgresql/data/
  #    <<: *default-logging
  restart: always

 redis:
  image: redis:6.0
  command:
   [
    'bash',
    '-c',
    'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"',
   ]
  env_file: ./judge0/judge0.conf
  volumes:
   - redis-data:/data
  #    <<: *default-logging
  restart: always

 apidb:
  image: postgres:latest
  restart: always
  ports:
   - '5432:5432'
  environment:
   - POSTGRES_USER=postgres
   - POSTGRES_PASSWORD=postgres
  healthcheck:
   test: ['CMD-SHELL', 'pg_isready -U postgres']
   interval: 1s
   timeout: 5s
   retries: 10
  volumes:
   - apidb:/var/lib/postgresql/data
  expose:
   - 5432
  networks:
   - mynet

 migration:
  image: api-migration
  build:
   context: .
   dockerfile: ./backend/drizzle-migration/Dockerfile
  depends_on:
   apidb:
    condition: service_healthy
  networks:
   - mynet
  environment:
   - DB_CONNECTION_STRING=postgres://postgres:postgres@apidb:5432/postgres

 backend:
  build:
   context: ./backend
   args:
    - DB_CONNECTION_STRING=postgres://postgres:postgres@apidb:5432/postgres
  image: saozp-backend
  restart: always
  depends_on:
   migration:
    condition: service_completed_successfully
  healthcheck:
   test: curl --fail http://localhost:3000 || exit 1
   interval: 30s
   timeout: 30s
   retries: 3
  networks:
   - mynet
  ports:
   - '3000:3000'
  links:
   - apidb
   - server
   - workers
  environment:
   - JUDGE0_HOST=server
   - JUDGE0_PORT=2358
   - ADMIN_LOGIN=admin
   - ADMIN_PASSWORD=admin
   - ADMIN_FIRST_NAME=Admin
   - ADMIN_LAST_NAME=Account
   - SESSION_LENGTH_IN_HOURS=5

 # corsproxy:
 #  build: ./corsproxy
 #  image: saozp-corsproxy
 #  restart: always
 #  networks:
 #   - mynet
 #  ports:
 #   - '80:80'

 frontend:
  build: ./frontend
  image: saozp-frontend
  restart: always
  depends_on:
   backend:
    condition: service_started
   # corsproxy:
   #  condition: service_started
  networks:
   - mynet
  ports:
   - '5173:80'
  links:
   - backend
  environment:
   - VITE_SAOZP_BACKEND_URL=backend

networks:
 mynet:
  driver: bridge

volumes:
 postgres-data:
 redis-data:
 apidb:
  driver: local
