services:
 apidb:
  image: postgres:16.2
  restart: always
  ports:
   - '5432:5432'
  environment:
   - POSTGRES_USER=${POSTGRES_USER}
   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  healthcheck:
   test: ['CMD-SHELL', 'pg_isready -U postgres']
   interval: 1s
   timeout: 5s
   retries: 10
  volumes:
   - apidb:/var/lib/postgresql/data
  expose:
   - 5432
  networks:
   - mynet

 migration:
  image: migration
  build:
   context: .
   dockerfile: ./backend/drizzle-migration/Dockerfile
  depends_on:
   apidb:
    condition: service_healthy
  networks:
   - mynet
  environment:
   - DB_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@apidb:5432/postgres

 proxy:
  build: ./proxy
  image: saozp-proxy
  restart: always
  networks:
   - mynet
  ports:
   - '5173:5173'
  links:
   - backend

 judgeclient:
  build: ./judgeclient
  image: judgeclient
  restart: always
  networks:
   - mynet
  ports:
   - '3002:3002'

 backend:
  build:
   context: ./backend
   args:
    - DB_CONNECTION_STRING=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@apidb:5432/postgres
  image: saozp-backend
  restart: always
  depends_on:
   migration:
    condition: service_completed_successfully
   judgeclient:
    condition: service_started
  healthcheck:
   test: curl --fail http://localhost:3000 || exit 1
   interval: 30s
   timeout: 30s
   retries: 3
  networks:
   - mynet
  ports:
   - '3000:3000'
  links:
   - apidb
  environment:
   - ADMIN_LOGIN=${ADMIN_LOGIN}
   - ADMIN_PASSWORD=${ADMIN_PASSWORD}
   - ADMIN_FIRST_NAME=${ADMIN_FIRST_NAME}
   - ADMIN_LAST_NAME=${ADMIN_LAST_NAME}
   - SESSION_LENGTH_IN_HOURS=${SESSION_LENGTH_IN_HOURS}

 frontend:
  build: ./frontend
  image: saozp-frontend
  restart: always
  depends_on:
   backend:
    condition: service_started
   proxy:
    condition: service_started
  networks:
   - mynet
  ports:
   - '3003:80'
  environment:
   - BACKEND_URL=${PUBLIC_IP}/api

networks:
 mynet:
  driver: bridge

volumes:
 data:
 apidb:
  driver: local
