table profiles {
  user_id integer [pk, not null]
  first_name varchar(32) [not null]
  last_name varchar(32) [not null]

  indexes {
    user_id [name: 'user_id_idx']
  }
}

table sessions {
  id uuid [pk, not null, default: `gen_random_uuid()`]
  user_id integer
  expiresAt "timestamp with time zone" [not null]

  indexes {
    id [name: 'session_id_idx']
  }
}

table users {
  id serial [pk, not null, increment]
  email varchar(256) [not null, unique]
  password varchar(128) [not null]

  indexes {
    email [name: 'email_idx']
  }
}

table problems {
  id serial [pk, not null, increment]
  creator_id integer [not null]
  name varchar(128) [not null]
  description varchar(512) [not null]
  prompt text [not null]
  language_id integer [not null]
  tests json [not null]
  base_code text [not null]
  deactivated boolean [not null, default: false]
}

table submissions {
  id serial [pk, not null, increment]
  problemId integer [not null]
  userId integer [not null]
  code text [not null]
  created_at timestamp [default: `now()`]
  is_commit boolean [not null, default: false]

  indexes {
    userId [name: 'submission_user_id_idx']
  }
}

table tests {
  token varchar(40) [pk, not null]
  submission_id integer [not null]
}

table admins {
  id integer [pk, not null]
}